services:
  api:
    networks:
      - default
      - edge

  client:
    networks:
      - default
      - edge

  homepage:
    networks:
      - default
      - edge

networks:
  edge:
    external: true
